version: '3.8'

services:
  consume:
    build: .
    container_name: consume
    image: "consume"
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db-consume
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      RMQ_HOST: ${RMQ_HOST}
      RMQ_USERNAME: ${RMQ_USERNAME}
      RMQ_PASSWORD: ${RMQ_PASSWORD}
      RMQ_EXCHANGE_NAME: ${RMQ_EXCHANGE_NAME}
      RMQ_EXCHANGE_KIND: ${RMQ_EXCHANGE_KIND}
    env_file:
      - .env
    depends_on:
      - db-consume
    networks:
      - backend
  
  db-consume: 
    container_name: db-consume
    image: postgres:15.2
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - backend
  
networks:
  backend:
    name: backend
    driver: bridge
    external: true

volumes:
  postgres-data:
    name: postgres-data-consume
